apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: metrics-example
  namespace: monitoring
  labels:
    prometheus: k8s
    role: alert-rules
spec:
  groups:
    - name: metrics-example.rules
      rules:
        - alert: ExampleAlert
          annotations:
            message: |
              Alert on: example_requests > 10
          expr: example_requests > 10
          labels:
            severity: none
