apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-redis"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-redis"
spec:
  serviceName: "{{ .Release.Name }}-redis"
  selector:
    matchLabels:
      release: "{{ .Release.Name }}-redis"
  replicas: 1
  template:
    metadata:
      labels:
        release: "{{ .Release.Name }}-redis"
    spec:
      containers:
        - name: redis
          image: redis
          resources:
            requests:
              cpu: 30m
              memory: 50Mi
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-redis"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-redis"
spec:
  selector:
    release: "{{ .Release.Name }}-redis"
  ports:
    - port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-counter"
spec:
  selector:
    matchLabels:
      release: "{{ .Release.Name }}-counter"
  replicas: 2
  template:
    metadata:
      labels:
        release: "{{ .Release.Name }}-counter"
    spec:
      containers:
        - name: counter
          image: "{{ .Values.image }}"
          resources:
            requests:
              cpu: 20m
              memory: 10Mi
          env:
            - name: REDIS
              value: "{{ .Release.Name }}-redis"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-counter"
spec:
  type: NodePort
  selector:
    release: "{{ .Release.Name }}-counter"
  ports:
    - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}"
spec:
  rules:
    - host: "{{ .Values.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-counter"
                port:
                  number: 80
