apiVersion: v1
kind: Pod
metadata:
  name: init-containers-setup
  labels:
    app: init-containers-setup
    svc: example
spec:
  volumes:
    - name: html
      emptyDir: {}
  initContainers:
    - name: setup
      image: debian
      volumeMounts:
        - name: html
          mountPath: /html
      command: ["/bin/sh", "-c"]
      args:
        - date > /html/index.html
      resources:
        requests:
          memory: 15Mi
          cpu: 10m
        limits:
          memory: 15Mi
          cpu: 10m
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      resources:
        requests:
          memory: 20Mi
          cpu: 30m
        limits:
          memory: 50Mi
          cpu: 30m
