apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: do-block-storage-retain
spec:
  storageClassName: do-block-storage-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
