apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-retain
spec:
  storageClassName: longhorn-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
