apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-1rep-pvc
spec:
  storageClassName: longhorn-1rep
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
