# https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/values.yaml
# https://artifacthub.io/packages/helm/bitnami/rabbitmq?modal=values

auth:
  username: admin
  password: admin
replicaCount: 3
ingress:
  enabled: true
  ingressClassName: nginx
  hostname: rabbitmq.k8s.cyber-crypt.com
  # TLS
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
