apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-user
  namespace: kube-system
secrets:
  - name: metrics-user
---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-user
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: metrics-user
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics
  namespace: kube-system
rules:
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics
subjects:
  - kind: ServiceAccount
    name: metrics-user
    namespace: kube-system
