apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: do-block-storage-retain
provisioner: dobs.csi.digitalocean.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
