apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp-protect-docker
spec:
  privileged: false # Don't allow privileged pods!
  allowPrivilegeEscalation: false
  # The rest fills in some required fields.
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
    - configMap
    - emptyDir
    - secret
    - projected
    - downwardAPI
  allowedHostPaths:
    # This specifies a whitelist of host paths that are allowed to be used by hostPath volumes. An empty list means there is no restriction on host paths used.
    - pathPrefix: "/tmp"
      readOnly: true
