apiVersion: v1
kind: ServiceAccount
metadata:
  name: root
  namespace: psp-example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-privileged
rules:
  - apiGroups:
      - policy
    resourceNames:
      - psp-root
    resources:
      - podsecuritypolicies
    verbs:
      - use
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-binding-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role-privileged
subjects:
  - kind: ServiceAccount
    name: root
    namespace: psp-example
