apiVersion: v1
kind: ServiceAccount
metadata:
  name: hacker
  namespace: psp-example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-unprivileged
rules:
  - apiGroups:
      - policy
    resourceNames:
      - psp-protect-docker
    resources:
      - podsecuritypolicies
    verbs:
      - use
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-binding-unprivileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role-unprivileged
subjects:
  - kind: ServiceAccount
    name: hacker
    namespace: psp-example
